GYMS_TR/Controllers/CategoriaController.cs
using GYMS_TR.Datos;
using GYMS_TR.Models;
using Microsoft.AspNetCore.Mvc;

namespace GYMS_TR.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ApplicationDbContext _context; //el Dbcontext es el que se va a en cargar de traerme la tabla //

        public CategoriaController(ApplicationDbContext context) // que estomo dicendo que que ven con la base detos //
        {
            _context = context;
        }

        public IActionResult CategoriaIndex()
        {
            IEnumerable<Categoria> lista = _context.Categorias;
            return View(lista);
        }

        [HttpGet]
        public IActionResult Crearcategoria() 
        { 
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crearcategoria(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _context.Categorias.Add(categoria);
                _context.SaveChanges();
                return RedirectToAction("CategoriaIndex");
            }
            return View(categoria);
        }

        [HttpGet]
        public IActionResult EditarCategoria(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var cg = _context.Categorias.Find(Id);

            if (cg ==null )
            {
                NotFound();
            }
            return View(cg);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditarCategoria(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _context.Update(categoria);
                _context.SaveChanges();
                return RedirectToAction("CategoriaIndex");
            }
            return View(categoria);
        }

        [HttpGet]
        public IActionResult EliminarCategoria(int? Id)
        {
            if(Id == null || Id == 0) 
            {
                return NotFound(); 
            }

            var cg = _context.Categorias.Find(Id);

            if (cg == null)
            {
                return NotFound();
            }

            return View(cg);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EliminarCategoria(Categoria categoria)
        {
            if (categoria == null)
            {
                return NotFound();
            }
            _context.Remove(categoria);
            _context.SaveChanges();
            return RedirectToAction("CategoriaIndex");
        }

    }
}

GYMS_TR/Controllers/ProductoController.cs
using GYMS_TR.Datos;
using GYMS_TR.Models;
using GYMS_TR.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace GYMS_TR.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IWebHostEnvironment _webHostEnvironment;//Esto es necesario para poder recibir ;a imagenes desde la vista hacia el controlador//

        public ProductoController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult ProductoIndex()
        {
            IEnumerable<Producto> lista = _context.Producto.Include(c => c.Categoria).
                                                             Include(t => t.TipoAplicacion);
            return View(lista);
        }

        [HttpGet]
        public IActionResult UpsertProducto(int? Id) 
        {
            /*Con es es una lista de la tabla caterio que le vamos enviar a la vista producto con el selectListItems.select
             esto quiere decir que va a enviar tanto texto como valor a la vista //
            IEnumerable<SelectListItem> categoriaLista = _context.Categorias.Select(c => new SelectListItem
            {
                Text = c.NombreCategoria,
                Value = c.Id.ToString()
            });
            ViewBag.categoriaLista = categoriaLista;

            Producto producto = new Producto();*/

            /*Aqui estamos inicializando nuestro ViewModle de producto y 
             estamos llamando todo lo que esta a dentro de ViewModel productop*/

            ProductoVM productoVM = new ProductoVM()
            {
                Producto = new Producto(),// Aqui estamos inicializando todo lo que tiene que lo que tiene a dentro//

                CategoriaLista = _context.Categorias.Select(c =>  new SelectListItem
                {
                    Text = c.NombreCategoria,
                    Value = c.Id.ToString()
                }),

                TipoAplicacionLista = _context.TipoAplicacion.Select(t => new SelectListItem
                {
                    Text = t.Nombre,
                    Value = t.Id.ToString()
                })

            };

            if (Id == null)// estamos dicendo con el Id que si llamos de el bonto crear //
            {
                //` cree un nuevo pruducto //
                return View(productoVM);
            }
            else
            {
                //Aqui esatmos diciendo qued si llamos el Id desde el bonto editar eso
                //quiere dicer que ahi producto en la lista.
                productoVM.Producto = _context.Producto.Find(Id);

                if (productoVM.Producto == null)// estamos que si no encontro ese registro o culumna de producta nos de una excepcion//
                {
                    return NotFound();
                }
            }

            return View(productoVM);//la vista tiene producto que haga la accion de editar//
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertProducto(ProductoVM productoVM)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;//este metodo es que va a resibir la imgende desde la vista//
                string wbRootPath = _webHostEnvironment.WebRootPath;//Aqui estamos diciendo que nos guarde la imagen en esta ruta//

                if (productoVM.Producto.Id == 0)//Aqui estamos deciendo que si el id del producto es igual a cero que nos cree un nuevo producto//
                {
                    //crear producto nuevo//
                    string upload = wbRootPath + WC.ImagenRuta;//Aqui esta guardando la imagen en la ruta que creamos en la carpeta wwwroot//
                    string fileName = Guid.NewGuid().ToString();// esta es para que le a signe un id a nuestra imagenes//
                    string extension = Path.GetExtension(files[0].FileName);//Aqui estamos recibiendo la imagen que agregamos//

                    using (var fileStream = new FileStream(Path.Combine(upload, fileName+extension),FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }

                    productoVM.Producto.ImageneUrl = fileName + extension;
                    _context.Producto.Add(productoVM.Producto);
                }
                else // Aqui estamos diceindo que el id es distinto o igual que  cero que Actualize el producto o editar//
                { 
                    //actualizar//
                    var objProducto = _context.Producto.AsNoTracking().FirstOrDefault(p => p.Id == productoVM.Producto.Id);//aqui lo que vamos hacer es que nos busque la imagen que vamos editar por el Id//

                    if (files.Count() > 0)//Aqui es que se va a cargar la imagen para crearla de nuevo//
                    {
                        string upload = wbRootPath + WC.ImagenRuta;//Aqui esta guardando la imagen en la ruta que creamos en la carpeta wwwroot//
                        string fileName = Guid.NewGuid().ToString();// esta es para que le a signe un id a nuestra imagenes//
                        string extension = Path.GetExtension(files[0].FileName);//Aqui estamos recibiendo la imagen que agregamos//

                        //Aqui se va a borrar la imagen que ya esta cargada //
                        var anteriorFile = Path.Combine(upload, objProducto.ImageneUrl);

                        if (System.IO.File.Exists(anteriorFile))//Aqui estamos diciendo que si la imagen existe borramela//
                        {
                            System.IO.File.Delete(anteriorFile);
                        }//fin de la imagen barrada anterior //

                        using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }

                        productoVM.Producto.ImageneUrl = fileName+extension;//Ya aqui estamos cargando la imagen nueva//
                    }//En caso contrario  no cargando una  nueva imagen//
                    else
                    {
                        productoVM.Producto.ImageneUrl = objProducto.ImageneUrl;
                    }
                    _context.Producto.Update(productoVM.Producto);

                }
                _context.SaveChanges();
                return RedirectToAction("ProductoIndex");
            }// este es la llame de ModelState.Isvalid//
            // esto es por si algo falla, que se llene las listas de categoria, tipoAplicacion
            productoVM.CategoriaLista = _context.Categorias.Select(c => new SelectListItem
            {
                Text = c.NombreCategoria,
                Value = c.Id.ToString()
            });

            productoVM.TipoAplicacionLista = _context.TipoAplicacion.Select(t => new SelectListItem
            {
                Text = t.Nombre,
                Value = t.Id.ToString()
            });
            return View(productoVM);
        }

        [HttpGet]
        public IActionResult EliminarProducto(int? Id)
        {
            if (Id == null || Id == 0)//Aqui estamos diciendo que si el Id es null o cero que devuelva no encontrado//
            {
                return NotFound();
            }

            Producto producto = _context.Producto.Include(c => c.Categoria)   //Aqui estamos diceindo que nos traiga ese registra por el Id seleciondo//
                                                    .Include(t => t.TipoAplicacion)
                                                    .FirstOrDefault(p => p.Id == Id);
            if (producto == null) //Aqui estamos diciendo que si no encontro el registro por el Id que nos diga no encontrado//
            {
                return NotFound();
            }

            return View(producto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EliminarProducto(Producto producto)
        {
            if (producto == null) 
            {
                return NotFound();
            }
            //Aui vamos a eliminar la imagen que esta agregadar//
            string upload =  _webHostEnvironment.WebRootPath + WC.ImagenRuta;
            
            //Aqui se va a borrar la imagen que ya esta cargada //
            var anteriorFile = Path.Combine(upload, producto.ImageneUrl);

            if (System.IO.File.Exists(anteriorFile))//Aqui estamos diciendo que si la imagen existe borramela//
            {
                System.IO.File.Delete(anteriorFile);
            }//fin de la imagen barrada anterior //

            _context.Producto.Remove(producto);
            _context.SaveChanges();
            return RedirectToAction("ProductoIndex");
        }
    }
}

GYMS_TR/Controllers/TipoAplicacionController.cs
using GYMS_TR.Datos;
using GYMS_TR.Models;
using Microsoft.AspNetCore.Mvc;

namespace GYMS_TR.Controllers
{
    public class TipoAplicacionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TipoAplicacionController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult TipoAplicacionIndex()
        {
            IEnumerable<TipoAplicacion> lista = _context.TipoAplicacion;
            return View(lista);
        }

        [HttpGet]
        public IActionResult CrearTipoAplicacion() 
        { 
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CrearTipoAplicacion(TipoAplicacion tipoAplicacion)
        {
            if (ModelState.IsValid)
            {
                _context.TipoAplicacion.Add(tipoAplicacion);
                _context.SaveChanges();

                return RedirectToAction("TipoAplicacionIndex");
            }
            return View(tipoAplicacion);
            
        }

        [HttpGet]
        public IActionResult EditarTipoAplicacion(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var tp = _context.TipoAplicacion.Find(Id);

            if (tp == null) 
            {
                return NotFound();
            }
            return View(tp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditarTipoAplicacion(TipoAplicacion tipoAplicacion)
        {
            if (ModelState.IsValid)
            {
                _context.TipoAplicacion.Update(tipoAplicacion);
                _context.SaveChanges();
                return RedirectToAction("TipoAplicacionIndex");
            }

            return View(tipoAplicacion);
        }

        [HttpGet]
        public IActionResult EliminarTipoAplicacion(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var tp = _context.TipoAplicacion.Find(Id);

            if (tp == null)
            {
                return NotFound();
            }
            return View(tp);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EliminarTipoAplicacion(TipoAplicacion tipoAplicacion)
        {
            if (tipoAplicacion == null)
            {
                return NotFound();
            }

            _context.TipoAplicacion.Remove(tipoAplicacion);
            _context.SaveChanges();
            return RedirectToAction("TipoAplicacionIndex");
        }


    }
}

GYMS_TR/Views/Shared/_Layout.cshtml
@*Aqui vamos autilizar algunas directivas para poder hacerde a las seciones*@
@using Microsoft.AspNetCore.Http
@*esto es para utilisar la siciones que ingreamos en el program y la carpeta de Utilidades*@
@inject IHttpContextAccessor HttpContextAccesor 
@using GYMS_TR.Utilidades


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GYMS_TR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GYMS_TR.styles.css" asp-append-version="true" />
    <link rel="stylesheet"  href="~/fontawesome/css/all.css"/>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GYMS_TR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between flex-row-reverse">
                    @*Aqui vamos agregar una vista parcial para que se muestre el todo lo que tiene que ver con el rister y login del usuario*@
                    <partial name="_LoginPartial"/>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Administral GYMS
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li> <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="CategoriaIndex">Categoria</a> </li>
                                <li> <a class="nav-link text-dark" asp-area="" asp-controller="TipoAplicacion" asp-action="TipoAplicacionIndex">Tipo Aplicacion</a> </li>
                                <li> <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="ProductoIndex">Pruducto</a> </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>

                        @*Aqui vamos hacer el proceso de ingresar los producto que seleccine el usuario ir guardandolo en el carro de compra// *@
                        <li>
                            @if (HttpContextAccesor.HttpContext.Session.Get<List<CarroCompra>>(WC.SessionCarroCompras) != null)//Esto aqui lo que va hacer un conteo de los producto que tiene el usuario en le carro de compra//
                            {
                                <a asp-action="CarroIndex" asp-controller="Carro" class="nav-link">
                                    @{
                                        var count = HttpContextAccesor.HttpContext.Session.Get<List<CarroCompra>>(WC.SessionCarroCompras).Count();
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            }
                            else
                            {
                             <a href="#" class="nav-link">
                                 <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                             </a>
                            }
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - GYMS_TR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GYMS_TR/Views/Shared/_ProductoCard.cshtml
@model GYMS_TR.Models.Producto

<div class="col-lg-4 col-md-6 pb-4  filter @Model.Categoria.NombreCategoria.Replace(' ','_')">@*Aqui estaremos Haciendo el filtro para buscar cada categoria por el nonmbre*@
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.NombreProducto</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@Model.Precio</span> / m &sup2;</label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WC.ImagenRuta@Model.ImageneUrl" alt="Imagen Card">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Categoria.NombreCategoria</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100 text-dark" style="background-color:aliceblue">@Model.TipoAplicacion.Nombre</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.DescripcionCorta</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Detalle" asp-route-Id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">Ver Detalle</a>
            </div>
        </div>
    </div>
</div>